/*
 * Project name:
     FirmwareIHM_v1_0.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     17/09/2018
 * Time of creation
     09:40:35
 * Test configuration:
     MCU:             P32MX795F512L
                      http://www.microchip.com/wwwproducts/Devices.aspx?product=PIC32MX795F512L
     Dev.Board:       PIC32MX7_MultiMedia_Board_9A
     Oscillator:      80000000 Hz
     SW:              mikroC PRO for PIC32
                      http://www.mikroe.com/mikroc/pic32/
 */

#include "FirmwareIHM_v1_0_objects.h"

void main() {

  Start_TP();

  while (1) {
    Check_TP();
  }
}
